# https://github.com/actions/setup-node
name: Build and test

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '21'
    - run: yarn install --frozen-lockfile
    - run: yarn test:lint
    - run: yarn test:unit
    - run: yarn cov:check
    - run: yarn build
    - run: yarn docs
